### ISSUE TITLE
Question: Validation of complex objects failing with NPM ERR

### ISSUE THREAD

**Issue by iambmelt** [trainiac/express-jsonschema#6]
I have three [simplified, for demonstrative purposes] schema objects defined.

Quiz

``` javascript
var quiz_schema = {
    "id": "/QuizSchema",
    "type": "object",
    "properties": {
        "name": {
            "type": 'string',
            "required": true
        },
        "questions": {
            "type": "array",
            "minItems": 1,
            "required": true,
            "items": {
                "$ref": "/QuestionSchema"
            }
        }
    }
};
```

Question

``` javascript
var question_schema = {
    "id": "/QuestionSchema",
    "type": "object",
    "properties": {
        "choices": {
            "type": "array",
            "minItems": 2,
            "required": true,
            "items": {
                "$ref": "/ChoiceSchema"
            }
        },
        "correct_choice": {
            "type": "string",
            "required": true
        },
        "text": {
            "type": 'string',
            "required": true
        },
        "img": {
            "type": 'string',
            "required": false
        },
        "img_alt": {
            "type": 'string',
            "required": false
        }
    }
};
```

Choice

``` javascript
var choice_schema = {
    "id": "/ChoiceSchema",
    "type": "object",
    "properties": {
        "text": {
            "type": "string",
            "required": true
        }
    }
};
```

The goal of which is to validate simple quizzes in JSON format of the following form:

``` json
{
    "name": "CS 101 - What's a computer?",
    "questions": [
        {
            "text": "Which of the following is not a form of storage media?",
            "choices": [
                {
                    "text": "Betamax"
                },
                {
                    "text": "CD-ROM"
                },
                {
                    "text": "BD-ROM"
                },
                {
                    "text": "Abraham Lincoln"
                }
            ],
            "correct_choice": "Abraham Lincoln"
        },
        {
            "text": "Which of the following computer scientists is not one of original developers of Unix?",
            "img": "https://upload.wikimedia.org/wikipedia/commons/1/1b/Abraham_Lincoln_November_1863.jpg",
            "img_alt": "Who is in this picture?",
            "choices": [
                {
                    "text": "Macho Man Randy Savage"
                },
                {
                    "text": "Ken Thompson"
                },
                {
                    "text": "Dennis Ritchie"
                },
                {
                    "text": "Brian Kernighan"
                }
            ],
            "correct_choice": "Macho Man Randy Savage"
        }
    ]
}
```

In my `quizzes.js` router, I attempt to perform this validation in the following way per this [example](https://www.npmjs.com/package/express-jsonschema#complex-example-with-split-schemas-and-references):

``` javascript
router.post('/', validate({ body: quizSchema }, [questionSchema, choiceSchema]), function (req, res) {
    // omitted
});
```

However, when I

``` shell
npm start
```

I get:

```
url.js:110
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url)
          ^
TypeError: Parameter 'url' must be a string, not number
    at Url.parse (url.js:110:11)
    at urlParse (url.js:104:5)
    at Object.urlResolve [as resolve] (url.js:437:10)
    at Validator.addSubSchema (/<PATH_TO_PROJECT>/node_modules/express-jsonschema/node_modules/jsonschema/lib/validator.js:61:36)
    at Validator.addSchema (/<PATH_TO_PROJECT>/node_modules/express-jsonschema/node_modules/jsonschema/lib/validator.js:42:8)
    at Array.forEach (native)
    at validate (/<PATH_TO_PROJECT>/node_modules/express-jsonschema/index.js:164:28)
    at Object.<anonymous> (/<PATH_TO_PROJECT>/routes/quizzes.js:29:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.5
npm ERR! code ELIFECYCLE
npm ERR! quizzical@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
```

I suspect that I'm running into trouble with the use of the `id` field - it looks like there's [conceivably](http://spacetelescope.github.io/understanding-json-schema/structuring.html) a great deal that this property is used for on the backend. Is there the expectation that all the schema files should be accessible over HTTP from `http[s]://<domain>/object.json` ?

Any help appreciated! :+1:

**Comment by DarynHolmes** [comment]
I am getting the same error....

**Comment by trainiac** [comment]
This has been fixed in https://github.com/trainiac/express-jsonschema/pull/15 and will be released shortly
